version: '3.8'

services:
   php:
    build:
     context: ./
    container_name: php
    hostname: php-container
    restart: unless-stopped
    volumes:
     - ./www:/var/www
    networks:
     - net
    healthcheck:
      test: curl -s http://nginx | grep works
      interval: 10s
      timeout: 5s
      retries: 5

   nginx:
    image: nginx
    container_name: nginx
    hostname: nginx-container
    restart: unless-stopped
    volumes:
      - ./nginx/dev.conf:/etc/nginx/conf.d/default.conf
      - ./www:/var/www
    ports:
      - 80:80
    networks:
      - net

networks:
 net:
